# Site
baseURL: "https://specttra.com.br"
languageCode: "pt-BR"
title: "Specttra"
googleAnalytics: "G-00HBCNRZ09"

# Custom variables
params:
  description: "Specttra - Soluções em Tecnologia"
  images: [site-feature-image.png]
  themeColor: "#000000"

# Build Configuration
cleanDestinationDir: true
disableHugoGeneratorInject: true
enableRobotsTXT: true
publishdir: "dist"
minify: true
disableKinds: [taxonomy, term, RSS]

# Virtual Modules
module:
  mounts:
    - source: content
      target: content

    - source: static
      target: static

    - source: layouts
      target: layouts

    - source: data
      target: data

    - source: assets
      target: assets

    - source: i18n
      target: i18n

    - source: archetypes
      target: archetypes

    - source: "node_modules/jquery/dist"
      target: "static/modules/jquery"
      includeFiles: ["jquery.min.js", "jquery.min.map"]
